version: 2.1

executors:
  cli:
    docker:
      - image: circleci/circleci-cli

jobs:
  validate_orbs:
    executor: cli
    steps:
      run: "scripts/validate_orbs.sh"

workflows:
  version: 2
  validate:
    jobs:
      - validate_orbs
