version: 2.1

executors:
  cli:
    docker:
      - image: circleci/circleci-cli

jobs:
  validate_orbs:
    executor: cli
    steps:
      - checkout
      - run: "scripts/validate_orbs.sh"
  publish_orbs:
    executor: cli
    steps:
      - checkout
      - run: "scripts/publish_bumped_orbs.sh"

workflows:
  version: 2
  build:
    jobs:
      - validate_orbs:
          branches:
            ignore:
              - master
      - publish_orbs:
          branches:
            only:
              - master
